# Generated by Django 5.2.7 on 2025-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
